import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between items-center">
          <Link href={'/home'}>
            Gogo Home
          </Link>
          <Link href={'/about'}>
            Gogo about
          </Link>
          <Link href={'/contact'}>
            Gogo contact
          </Link>
        </div>
        {children}
        
        </body>
    </html>
  );
}
